### ISSUE TITLE
Integrate with VirtualBox

### ISSUE THREAD

**Issue by PythonNut** [PythonNut/virtualbox-remote-snapshots#1]
Currently, there is a lot to be gained by integrating with the hypervisor. This is a tracker issue.

- [x] Use `VirtualBox` to find VMs #3
- [x] Use `VirtualBox` to ensure snapshot crash-consistency #17 
- [x] Use `VirtualBox` to annotate snapshots with important metadata #16 
- [x] Use `VirtualBox` to ensure that a VM is offline during a restore. #18
